name: Build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone repository
        uses: actions/checkout@main

      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Build electron app
        id: info
        run: |
          sudo apt update && sudo apt install libarchive-tools libvips-dev
          npm install
          npm run dist

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@master
        with:
          body_path: release.md
          append_body: true
          draft: false
          files: |
            dist/*.AppImage
            dist/*.pacman
            dist/latest*.yml

      - name: Upload to artifacts - ARM
        uses: actions/upload-artifact@main
        with:
          name: App - ARM
          path: |
            dist/*armv7l*.AppImage
            dist/*latest-linux-arm.yml

      - name: Upload to artifacts - x64
        uses: actions/upload-artifact@main
        with:
          name: App - x64
          path: |
            dist/*x*64*.AppImage
            dist/*.pacman
            dist/latest-linux.yml